/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as sudokuSol from "./Sudoku.sol";
export { SudokuVerifier__factory } from "./SudokuVerifier__factory";
